# Main configuration file for Fancier Block Particles
# I advise to use the in game configuration pages instead of manually editing this file

enabled: true

# Particles Config:

minAge: 10
maxAge: 64
showInMillis: false
infiniteDuration: false
particlesPerAxis: 4
scaleMult: 0.75
gravityMult: 1.0
rotationMult: 1.0
randomRotation: true
randomizedScale: true
randomFadingSpeed: true
spawnWhileFrozen: true
entityCollision: true
bounceOffWalls: true
lowTraction: false
smartBreaking: true
fancyFlame: false
fancySmoke: false
waterPhysics: true

# Fancy Block Placement Config:

fancyPlaceAnim: true
spawnPlaceParticles: true

# Weather Config:

fancyWeather: false
dynamicWeather: false
weatherParticleDensity: 1.0
weatherRenderDistance: 1.0

# Experiments:

experiments: false

# Debug Config:

debugMode: false